server:
  port: 8080
  # servlet:
    # context-path: /api/v1

spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/foodorder
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      secret: ${JWT_SECRET:your-256-bit-secret-key-here}
      expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    root: INFO
    com.foodorder.usermanagement: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG 